brands = ["ALFA ROMEO",
    "ASTON MARTIN",
    "AUDI",
    "BAIC",
    "BESTUNE",
    "BMW",
    "BRILLIANCE",
    "BUGATTI",
    "BYD",
    "CADILLAC",
    "CHANA",
    "CHANGAN",
    "CHERY",
    "CHEVROLET",
    "CHRYSLER",
    "CITROEN",
    "CORVETTE",
    "CUPRA",
    "DACIA",
    "DAEWOO",
    "DAIHATSU",
    "DFM",
    "DFSK",
    "DF_JOYEAR",
    "DODGE",
    "DONGFENG",
    "DS",
    "EMGRAND",
    "FAW",
    "FERRARI",
    "FIAT",
    "FIAT PROFESSIONAL",
    "FORD",
    "FOTON",
    "GEELY",
    "GONOW",
    "GREAT WALL",
    "HAFEI MOTORS",
    "HAIMA",
    "HONDA",
    "HUMMER",
    "HYUNDAI",
    "INFINITI",
    "IRAN KHODRO",
    "ISUZU",
    "JAC",
    "JAGUAR",
    "JEEP",
    "JETOUR",
    "JMC",
    "KAIYI",
    "KIA",
    "LADA",
    "LAMBORGHINI",
    "LANCIA",
    "LAND ROVER",
    "LEXUS",
    "LIFAN",
    "LIVAN",
    "MAHINDRA",
    "MARQUE VOITURE JETTA",
    "MASERATI",
    "MAZDA",
    "MCLAREN",
    "MERCEDES",
    "MG",
    "MINI",
    "MITSUBISHI",
    "NISSAN",
    "OPEL",
    "PEUGEOT",
    "PORSCHE",
    "RENAULT",
    "ROLLS ROYCE",
    "ROVER",
    "SAAB",
    "SAIPA",
    "SEAT",
    "SKODA",
    "SMART",
    "SOKON",
    "SSANGYONG",
    "SUBARU",
    "SUZUKI",
    "TATA",
    "TOYOTA",
    "VICTORY_AUTO",
    "VOLKSWAGEN",
    "VOLVO",
    "ZOTYE"]
module.exports = brands;